# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sessionid',
            field=models.CharField(default=12345, max_length=200),
            preserve_default=False,
        ),
    ]
